### ISSUE TITLE
Running `npm install @colap-dev/ngx-britecharts britecharts` installs an empty dependency

### ISSUE THREAD

**Issue by MaheshCasiraghi** [colapdev/ngx-britecharts#1]
No files are published to npm

**Comment by martinmanzo** [comment]
Hi @MaheshCasiraghi, thanks for your interest in this package.

We are waiting for Britecharts to publish a new version of their package and we will then publish the first beta version of ngx-britecharts.

**Comment by martinmanzo** [comment]
Hi @MaheshCasiraghi, we just published the first version. Not all charts are available but you'll get a sense of what's going on by reading the README.
